let state=load()||{version:1,object:{},buildings:[]}; let currentView='object',currentBuilding=null,currentUnit=null;
function uid(){return Math.random().toString(36).slice(2,10)}
function save(){localStorage.setItem('wertaufnahme-v1',JSON.stringify(state));document.getElementById('saveStatus').textContent='gespeichert · '+new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}
function load(){try{return JSON.parse(localStorage.getItem('wertaufnahme-v1'))}catch(e){return null}}
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function getObj(){if(currentView==='object')return state.object;if(currentView==='buildings')return state.buildings.find(b=>b.id===currentBuilding)?.data;if(currentView==='units'){let b=state.buildings.find(b=>b.id===currentBuilding);return b?.units.find(u=>u.id===currentUnit)?.data}return null}
function setVal(key,val){const o=getObj();if(!o)return;o[key]=val;save();renderTree();}
function renderField(f,o){const v=o?.[f.key]??(f.type==='multi'?[]:'');let html=`<div class="field"><label>${esc(f.label)}</label>`;if(f.type==='textarea')html+=`<textarea data-key="${f.key}">${esc(v)}</textarea>`;else if(['text','number','date','time'].includes(f.type))html+=`<input type="${f.type}" data-key="${f.key}" value="${esc(v)}">`;else{html+=`<div class="choices">`;for(const opt of f.options){const checked=f.type==='multi'?Array.isArray(v)&&v.includes(opt):v===opt;html+=`<label class="choice"><input type="${f.type==='multi'?'checkbox':'radio'}" data-key="${f.key}" value="${esc(opt)}" ${checked?'checked':''}><span>${esc(opt)}</span></label>`}html+=`</div>`}if(f.help)html+=`<div class="hint">${esc(f.help)}</div>`;return html+`</div>`}
function bindInputs(){document.querySelectorAll('[data-key]').forEach(el=>{el.addEventListener('change',e=>{const key=e.target.dataset.key; if(e.target.type==='checkbox'){const o=getObj();let arr=Array.isArray(o[key])?[...o[key]]:[]; if(e.target.checked&&!arr.includes(e.target.value))arr.push(e.target.value);if(!e.target.checked)arr=arr.filter(x=>x!==e.target.value);setVal(key,arr)}else setVal(key,e.target.value)}); if(el.tagName==='TEXTAREA'||['text','number','date','time'].includes(el.type))el.addEventListener('input',e=>setVal(e.target.dataset.key,e.target.value))})}
function completeness(sections,data){let total=0,done=0;sections.forEach(s=>s.fields.forEach(f=>{total++;const v=data?.[f.key];if(Array.isArray(v)?v.length>0:String(v??'').trim()!=='')done++}));return total?Math.round(done/total*100):0}
function page(title,subtitle,sections,data,actions=''){const pct=completeness(sections,data||{});return `<div class="card hero"><div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p><div class="progress"><span style="width:${pct}%"></span></div><div class="hint">${pct}% der Felder belegt</div></div><div class="actions">${actions}</div></div>`+sections.map(s=>`<section class="card section"><h2>${esc(s.title)}</h2><div class="grid">${s.fields.map(f=>renderField(f,data||{})).join('')}</div></section>`).join('')}
function renderTree(){const t=document.getElementById('tree');let h=`<div class="treehead"><span>Objektstruktur</span><button class="tiny" onclick="addBuilding()">+ Gebäude</button></div>`;if(!state.buildings.length)h+=`<div class="hint" style="padding:8px">Noch kein Gebäude angelegt.</div>`;state.buildings.forEach((b,i)=>{h+=`<button class="treebtn ${currentView==='buildings'&&currentBuilding===b.id?'active':''}" onclick="openBuilding('${b.id}')">${esc(b.name||'Gebäude '+(i+1))}</button>`;b.units.forEach((u,j)=>h+=`<button class="treebtn treeunit ${currentView==='units'&&currentUnit===u.id?'active':''}" onclick="openUnit('${b.id}','${u.id}')">↳ ${esc(u.name||'Einheit '+(j+1))}</button>`);h+=`<div style="padding:0 10px 6px"><button class="tiny" onclick="addUnit('${b.id}')">+ Einheit</button></div>`});t.innerHTML=h}
function addBuilding(){const n=state.buildings.length+1,b={id:uid(),name:'Gebäude '+n,data:{},units:[]};state.buildings.push(b);currentBuilding=b.id;currentView='buildings';save();syncNav();render()}
function addUnit(bid){const b=state.buildings.find(x=>x.id===bid);if(!b)return;const u={id:uid(),name:'Einheit '+(b.units.length+1),data:{}};b.units.push(u);currentBuilding=bid;currentUnit=u.id;currentView='units';save();syncNav();render()}
function openBuilding(id){currentBuilding=id;currentView='buildings';syncNav();render()}
function openUnit(bid,uidv){currentBuilding=bid;currentUnit=uidv;currentView='units';syncNav();render()}
function renameBuilding(id){const b=state.buildings.find(x=>x.id===id);if(!b)return;const n=prompt('Bezeichnung des Gebäudes',b.name);if(n!==null&&n.trim()){b.name=n.trim();save();render()}}
function renameUnit(bid,uidv){const u=state.buildings.find(x=>x.id===bid)?.units.find(x=>x.id===uidv);if(!u)return;const n=prompt('Bezeichnung der Nutzungseinheit',u.name);if(n!==null&&n.trim()){u.name=n.trim();save();render()}}
function removeBuilding(id){if(!confirm('Gebäude inklusive aller Einheiten löschen?'))return;state.buildings=state.buildings.filter(x=>x.id!==id);currentBuilding=state.buildings[0]?.id||null;currentView=state.buildings.length?'buildings':'object';save();syncNav();render()}
function removeUnit(bid,uidv){if(!confirm('Diese Nutzungseinheit löschen?'))return;const b=state.buildings.find(x=>x.id===bid);b.units=b.units.filter(x=>x.id!==uidv);currentUnit=b.units[0]?.id||null;currentView=currentUnit?'units':'buildings';save();syncNav();render()}
function render(){renderTree();const m=document.getElementById('main');if(currentView==='object'){m.innerHTML=page('Objekt & Lage','Erfassungsbogen Teil 1 · Grund / Boden',p1,state.object)}else if(currentView==='buildings'){let b=state.buildings.find(x=>x.id===currentBuilding)||state.buildings[0];if(!b){m.innerHTML=`<div class="card empty">Noch kein Gebäude vorhanden.<br><br><button class="btn primary" onclick="addBuilding()">Erstes Gebäude anlegen</button></div>`;return}currentBuilding=b.id;const acts=`<button class="btn" onclick="renameBuilding('${b.id}')">Umbenennen</button><button class="btn primary" onclick="addUnit('${b.id}')">+ Einheit</button><button class="btn danger" onclick="removeBuilding('${b.id}')">Löschen</button>`;m.innerHTML=page(b.name,'Erfassungsbogen Teil 2 · Gebäudebeschreibung',p2,b.data,acts)}else if(currentView==='units'){let b=state.buildings.find(x=>x.id===currentBuilding);let u=b?.units.find(x=>x.id===currentUnit);if(!u){m.innerHTML=`<div class="card empty">Bitte zuerst eine Nutzungseinheit anlegen.</div>`;return}const acts=`<button class="btn" onclick="renameUnit('${b.id}','${u.id}')">Umbenennen</button><button class="btn danger" onclick="removeUnit('${b.id}','${u.id}')">Löschen</button>`;m.innerHTML=page(u.name,`${b.name} · Erfassungsbogen Teil 3 · Ausstattung`,p3,u.data,acts)}else renderExport();bindInputs()}
function flatten(prefix,obj,out){Object.entries(obj||{}).forEach(([k,v])=>out[prefix+k]=Array.isArray(v)?v.join(' | '):v)}
function rowsForCSV(){const rows=[];let base={Ebene:'Objekt',Gebäude:'',Einheit:''};flatten('Lage_',state.object,base);rows.push(base);state.buildings.forEach(b=>{let r={Ebene:'Gebäude',Gebäude:b.name,Einheit:''};flatten('Gebäude_',b.data,r);rows.push(r);b.units.forEach(u=>{let q={Ebene:'Einheit',Gebäude:b.name,Einheit:u.name};flatten('Einheit_',u.data,q);rows.push(q)})});return rows}
function toCSV(rows){const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))];const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return '\ufeff'+cols.map(q).join(';')+'\n'+rows.map(r=>cols.map(c=>q(r[c])).join(';')).join('\n')}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJSON(){download('Wertaufnahme_'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(state,null,2),'application/json')}
function exportCSV(){download('Wertaufnahme_'+new Date().toISOString().slice(0,10)+'.csv',toCSV(rowsForCSV()),'text/csv;charset=utf-8')}
function importJSON(inp){const f=inp.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const s=JSON.parse(r.result);if(!s||!Array.isArray(s.buildings))throw new Error();state=s;save();currentView='object';currentBuilding=null;currentUnit=null;syncNav();render();alert('Projekt wurde importiert.')}catch(e){alert('Die Projektdatei konnte nicht gelesen werden.')}};r.readAsText(f)}
function resetAll(){if(confirm('Alle lokal gespeicherten Daten dieses Projekts wirklich löschen?')){state={version:1,object:{},buildings:[]};save();currentView='object';syncNav();render()}}
function summaryHtml(){let h=`<section class="card section"><h2>Objektstruktur</h2><p><strong>${esc(state.object.objectAddress||'Objekt ohne Anschrift')}</strong></p><p>${state.buildings.length} Gebäude · ${state.buildings.reduce((n,b)=>n+b.units.length,0)} Nutzungseinheiten</p></section>`;state.buildings.forEach(b=>{h+=`<section class="card section"><h2>${esc(b.name)}</h2><p><span class="badge">Gebäude ${completeness(p2,b.data)}%</span></p><p>${b.units.map(u=>`${esc(u.name)} (${completeness(p3,u.data)}%)`).join(' · ')||'Keine Einheiten'}</p></section>`});return h}
function renderExport(){document.getElementById('main').innerHTML=`<div class="card hero"><div><h1>Export & Datensicherung</h1><p>Projekt sichern oder für die Übertragung in die Gutachtensoftware ausgeben.</p></div></div>${summaryHtml()}<section class="card section"><h2>Ausgabe</h2><div class="actions"><button class="btn primary" onclick="exportJSON()">Projektdatei (.json)</button><button class="btn" onclick="exportCSV()">Tabellendatei (.csv)</button><button class="btn" onclick="window.print()">Druckansicht / PDF</button><label class="btn">Projekt importieren<input class="hidden" type="file" accept="application/json,.json" onchange="importJSON(this)"></label></div><div class="exportbox"><strong>Projektdatei</strong>: vollständige Datensicherung und späteres Weiterarbeiten.<br><strong>CSV</strong>: flache Tabellenstruktur für Excel oder einen späteren Import in die Gutachtensoftware.<br><strong>Druckansicht</strong>: schnelle Dokumentation für die Akte.</div></section><section class="card section"><h2>Projektverwaltung</h2><button class="btn danger" onclick="resetAll()">Lokale Daten löschen</button></section>`}
function syncNav(){document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView))}
document.querySelectorAll('.navbtn').forEach(b=>b.addEventListener('click',()=>{currentView=b.dataset.view;if(currentView==='buildings'&&!currentBuilding)currentBuilding=state.buildings[0]?.id||null;if(currentView==='units'&&!currentUnit){const b=state.buildings[0];currentBuilding=b?.id||null;currentUnit=b?.units[0]?.id||null}syncNav();render()}));
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
