const PHOTO_DB='wertaufnahme-media-v1', PHOTO_STORE='photos';
function openPhotoDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(PHOTO_DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(PHOTO_STORE)){const s=db.createObjectStore(PHOTO_STORE,{keyPath:'id'});s.createIndex('projectId','projectId',{unique:false});s.createIndex('scope','scopeKey',{unique:false})}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function photoTx(mode,fn){const db=await openPhotoDB();return new Promise((resolve,reject)=>{const tx=db.transaction(PHOTO_STORE,mode),store=tx.objectStore(PHOTO_STORE);let val;try{val=fn(store)}catch(e){reject(e);return}tx.oncomplete=()=>resolve(val);tx.onerror=()=>reject(tx.error)})}
async function addPhoto(projectId,scopeType,scopeId,file,note=''){const rec={id:'ph_'+Date.now()+'_'+Math.random().toString(36).slice(2,8),projectId,scopeType,scopeId,scopeKey:projectId+'|'+scopeType+'|'+scopeId,name:file.name||'Foto',type:file.type||'image/jpeg',size:file.size||0,createdAt:new Date().toISOString(),note,blob:file};await photoTx('readwrite',s=>s.put(rec));return rec}
async function listPhotos(projectId,scopeType,scopeId){const db=await openPhotoDB();return new Promise((resolve,reject)=>{const tx=db.transaction(PHOTO_STORE,'readonly'),idx=tx.objectStore(PHOTO_STORE).index('scope'),req=idx.getAll(projectId+'|'+scopeType+'|'+scopeId);req.onsuccess=()=>resolve((req.result||[]).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)));req.onerror=()=>reject(req.error)})}
async function listProjectPhotos(projectId){const db=await openPhotoDB();return new Promise((resolve,reject)=>{const tx=db.transaction(PHOTO_STORE,'readonly'),idx=tx.objectStore(PHOTO_STORE).index('projectId'),req=idx.getAll(projectId);req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}
async function deletePhoto(id){await photoTx('readwrite',s=>s.delete(id))}
async function updatePhotoNote(id,note){const db=await openPhotoDB();return new Promise((resolve,reject)=>{const tx=db.transaction(PHOTO_STORE,'readwrite'),s=tx.objectStore(PHOTO_STORE),g=s.get(id);g.onsuccess=()=>{const r=g.result;if(r){r.note=note;s.put(r)}};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function deleteProjectPhotos(projectId){const rows=await listProjectPhotos(projectId);await photoTx('readwrite',s=>rows.forEach(r=>s.delete(r.id)))}
function blobToDataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
function dataURLToBlob(dataURL){const [head,b64]=dataURL.split(',');const type=(head.match(/data:(.*?);/)||[])[1]||'application/octet-stream';const bin=atob(b64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type})}
